- 배열 연산의 활용
- 계단 중간에서 같은 확률로 한 계단 올라가거나 내려간다
- 계단 오르내리기는 오르기(+1)와 내리기(-1)의 누적합이다. 
- np.module을 사용해서 1000번 수행한 결과 (1, -1)을 한 번에 저장하고 누적합을 계산한다. 

In [8]:
import numpy as np

In [9]:
nsteps = 1000  # 계단 오르내리기 1000번 수행

draws = np.random.randint(0, 2, size = nsteps)  # 0~1까지의 랜덤 숫자 size개 뽑아내기

steps = np.where(draws > 0, 1, -1)  # draw가 0이면 -1, 1이면 1

walk = steps.cumsum()  # step의 누적합

In [10]:
walk

array([ -1,  -2,  -3,  -4,  -3,  -4,  -3,  -2,  -1,   0,  -1,  -2,  -1,
        -2,  -1,  -2,  -3,  -2,  -3,  -4,  -5,  -6,  -5,  -4,  -3,  -2,
        -3,  -2,  -1,   0,   1,   2,   1,   2,   1,   0,  -1,   0,   1,
         2,   3,   2,   3,   4,   5,   4,   3,   2,   1,   2,   3,   4,
         3,   4,   5,   4,   3,   4,   3,   2,   1,   0,  -1,  -2,  -3,
        -4,  -3,  -4,  -3,  -2,  -1,  -2,  -1,   0,  -1,  -2,  -1,   0,
         1,   0,  -1,   0,  -1,   0,  -1,   0,  -1,  -2,  -1,   0,   1,
         2,   1,   2,   1,   0,   1,   2,   1,   0,   1,   0,   1,   0,
         1,   0,   1,   2,   3,   4,   5,   4,   5,   4,   5,   4,   3,
         2,   1,   2,   1,   2,   1,   2,   3,   2,   1,   2,   1,   2,
         1,   2,   3,   2,   3,   4,   3,   4,   5,   4,   5,   4,   3,
         2,   1,   0,   1,   2,   3,   2,   3,   2,   1,   2,   3,   2,
         3,   4,   3,   4,   5,   6,   7,   8,   7,   6,   5,   6,   5,
         4,   5,   6,   7,   6,   5,   6,   5,   4,   5,   4,   

In [11]:
walk.min()  # 계단을 오르내린 위치의 최솟값

-17

In [12]:
walk.max()  # 계단을 오르내린 위치의 최댓값

17

In [14]:
#---- 계단에서 특정 위치에 도달하기까지의 시간
(np.abs(walk) >= 10).argmax()  # 처음에서 10간 이상 떨어진 걸음부터 True로 한다. 최초로 10칸 이상 떨어진적이 몇번째인지 알자

221

계단 오르내리기를 많은 횟수(5000번) 시뮬레이션
- numpy.random 함수으ㅔ 크기가 2인 튜플을 넘기면 2차원 배열이 생성되고 각 컬럼에서 누적합을 구하기

In [18]:
nwalks = 5000

nstep = 1000

draws = np.random.randint(0, 2, size = (nwalks, nsteps))  # 0또는 1로 구성된 5000행, 1000열을 만든다

steps = np.where(draws > 0, 1, -1)

walks = steps.cumsum(1)

walks

array([[ -1,  -2,  -3, ..., -32, -31, -30],
       [ -1,   0,  -1, ..., -50, -49, -48],
       [  1,   0,  -1, ...,  24,  23,  22],
       ...,
       [  1,   0,   1, ...,  18,  17,  16],
       [  1,   2,   1, ...,  -4,  -3,  -4],
       [  1,   2,   1, ...,   6,   7,   8]], dtype=int32)

In [19]:
walk.shape

(1000,)

In [20]:
walks.max()

118

In [21]:
walks.min()

-105

In [22]:
# 누적합이 30 또는 -30이 되는 최소 시점 계산하기
hist30 = (np.abs(walks) >= 30).any(1)

In [23]:
hist30

array([ True,  True, False, ..., False, False, False])

In [24]:
hist30.sum()

3371

In [25]:
crossing_times = (np.abs(walks[hist30]) >= 30).argmax(1)

In [26]:
crossing_times.mean()

501.5398991397212