4.1.NumPy ndarray:multi-dimension array object

In [1]:
import numpy as np

#---- 스칼라값과 유사한 배치 계산 처리
# 임의의 값을 생성
data = np.random.randn(2, 3)
data

array([[-1.16522301, -0.06486468,  0.32781042],
       [ 0.45696441,  0.78026184, -1.12282589]])

In [2]:
data * 10

array([[-11.65223012,  -0.64864675,   3.27810424],
       [  4.56964407,   7.80261843, -11.22825891]])

In [3]:
data + data

array([[-2.33044602, -0.12972935,  0.65562085],
       [ 0.91392881,  1.56052369, -2.24565178]])

In [4]:
#---- shape 튜플
data.shape

(2, 3)

In [5]:
#---- dtype 객체
data.dtype

dtype('float64')

4.1.1.ndarray 생성하기

In [6]:
#---- array 함수를 이용하여 배열 생성
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
# 같은 길이의 리스트를 다차원 배열로 변환
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# np.array는 데이터를 추론하여 형태와 적절한 자료형을 지정한다. 
arr2.ndim # ndim 속성

2

In [9]:
arr2.shape # shape 속성

(2, 4)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

In [12]:
#---- 배열 생성 함수
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# asarray와 array
arr3 = np.arange(15)
arrA = np.array(arr3)
arrB = np.asarray(arr3)

In [17]:
arrA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arrB

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr3[0] = 9

In [20]:
arrA # array는 복사본 형성

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arrB # asarray는 참조본 생성

array([ 9,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.full((2,2), [1,8], dtype = int)

array([[1, 8],
       [1, 8]])

In [23]:
np.eye(3, k = 0, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
np.eye(3, k = 1, dtype = int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [25]:
np.eye(3, k= -1, dtype = int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

4.1.2. dtype of ndarray

In [26]:
#---- NumPy 자료형
# dtype 객체
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)

arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
# astype 메서드 
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [30]:
float_arr

array([1., 2., 3., 4., 5.])

In [31]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [32]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [33]:
# 다른 배열의 dtype 속성 이용하기
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50])
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.1.3. NumPy 배열의 산술 연산

In [35]:
#---- NumPy의 벡터화
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [37]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [39]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [40]:
arr2 = np.array([[1, 5, 3], [6, 2, 3]])
arr2

array([[1, 5, 3],
       [6, 2, 3]])

In [41]:
arr > arr2

array([[False, False, False],
       [False,  True,  True]])

4.1.4. 색인과 슬라이싱 기초

In [42]:
#---- NumPy의 색인과 슬라이싱
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5]

5

In [44]:
arr[5:8]

array([5, 6, 7])

In [45]:
arr[5:8] = 12

In [46]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [47]:
# 배열 조각은 원본 배열의 뷰이다
arr_slice = arr[5:8]

arr_slice

array([12, 12, 12])

In [48]:
arr_slice[1] = 12345

arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [49]:
arr_slice[:] = 64

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [50]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[2]

array([7, 8, 9])

In [51]:
arr2d[0][2]

3

In [52]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9,], [10, 11, 12]]])
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
old_values = arr3d[0].copy()
arr3d[0] = 42

In [54]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
#---- 슬라이스로 선택하기
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [58]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

4.1.5. 불리언값으로 선택하기

In [60]:
names = np.array(['Jason', 'Jimin', 'Mini', 'Bob', 'Bob', 'Jason', 'Bob'])
data = np.random.randn(7, 4)

In [61]:
names

array(['Jason', 'Jimin', 'Mini', 'Bob', 'Bob', 'Jason', 'Bob'],
      dtype='<U5')

In [62]:
data

array([[-0.54938693,  2.51374854,  1.94623063, -0.47154044],
       [-0.4450687 , -0.52761627,  0.59758637, -1.39109955],
       [-0.70533132,  0.8341502 , -1.04386163, -0.53459518],
       [ 0.80193116, -0.95558476,  0.5342767 ,  0.37767391],
       [ 0.33981744, -1.26402071, -1.13929656, -0.07444128],
       [ 0.97688249, -1.16794964, -1.37230611,  1.62645235],
       [-0.15675635,  0.2319883 , -0.52984984, -0.32839043]])

In [63]:
# 불리언 배열을 색인으로 사용하기
data[names == 'Bob']

array([[ 0.80193116, -0.95558476,  0.5342767 ,  0.37767391],
       [ 0.33981744, -1.26402071, -1.13929656, -0.07444128],
       [-0.15675635,  0.2319883 , -0.52984984, -0.32839043]])

In [64]:
data[names == 'Bob', 2:]

array([[ 0.5342767 ,  0.37767391],
       [-1.13929656, -0.07444128],
       [-0.52984984, -0.32839043]])

In [65]:
data[names == 'Bob', 3]

array([ 0.37767391, -0.07444128, -0.32839043])

In [66]:
names!='Bob'

array([ True,  True,  True, False, False,  True, False])

In [67]:
data[~(names == 'Bob')]

array([[-0.54938693,  2.51374854,  1.94623063, -0.47154044],
       [-0.4450687 , -0.52761627,  0.59758637, -1.39109955],
       [-0.70533132,  0.8341502 , -1.04386163, -0.53459518],
       [ 0.97688249, -1.16794964, -1.37230611,  1.62645235]])

In [68]:
cond = names =='Bob'
data[~cond]

array([[-0.54938693,  2.51374854,  1.94623063, -0.47154044],
       [-0.4450687 , -0.52761627,  0.59758637, -1.39109955],
       [-0.70533132,  0.8341502 , -1.04386163, -0.53459518],
       [ 0.97688249, -1.16794964, -1.37230611,  1.62645235]])

In [69]:
mask = (names == 'Bob') | (names == 'Jason')
mask

array([ True, False, False,  True,  True,  True,  True])

In [70]:
data[mask]

array([[-0.54938693,  2.51374854,  1.94623063, -0.47154044],
       [ 0.80193116, -0.95558476,  0.5342767 ,  0.37767391],
       [ 0.33981744, -1.26402071, -1.13929656, -0.07444128],
       [ 0.97688249, -1.16794964, -1.37230611,  1.62645235],
       [-0.15675635,  0.2319883 , -0.52984984, -0.32839043]])

In [72]:
data[data<0] = 0

In [73]:
data

array([[0.        , 2.51374854, 1.94623063, 0.        ],
       [0.        , 0.        , 0.59758637, 0.        ],
       [0.        , 0.8341502 , 0.        , 0.        ],
       [0.80193116, 0.        , 0.5342767 , 0.37767391],
       [0.33981744, 0.        , 0.        , 0.        ],
       [0.97688249, 0.        , 0.        , 1.62645235],
       [0.        , 0.2319883 , 0.        , 0.        ]])

In [74]:
data[names != 'Joe'] = 7
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [75]:
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

4.1.6. 팬시 색인

In [76]:
arr = np.empty((8, 4))
for i in range(8) : 
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [77]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [78]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [79]:
# 다차원 색인 배열 넘기기
arr = np.arange(32).reshape((8, 4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [81]:
arr[[1, 5, 7, 2]][:,[0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

4.1.7. 배열 전치와 축 바꾸기

In [82]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [84]:
# 행렬의 내적
arr = np.random.randn(6, 3)

arr

array([[ 0.09563744, -1.25191103, -1.73940894],
       [-0.91209533, -1.37771301, -1.47223519],
       [ 0.41266629,  0.43485259,  2.10108071],
       [ 1.08870328, -0.5391935 ,  0.8460073 ],
       [-0.16331197, -0.67440821,  0.73879843],
       [-0.238739  ,  1.03290224, -0.43544955]])

In [85]:
np.dot(arr.T, arr)

array([[ 2.28029981,  0.5928482 ,  2.94786648],
       [ 0.5928482 ,  5.46691423,  3.71537301],
       [ 2.94786648,  3.71537301, 11.05872785]])

In [87]:
# transpose 메서드

4.2. 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수

In [88]:
#---- ufunc
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [90]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [91]:
# 이항 유니버설 함수
x = np.random.randn(8)
y = np.random.randn(8)

In [92]:
x

array([-0.65693942,  2.00236875,  0.10059244,  0.14863274,  0.71001077,
        0.9974245 ,  1.12337863, -1.21302593])

In [93]:
y

array([ 0.2973398 , -0.64265276, -1.1756963 , -0.40736297, -0.27467943,
        0.00255291,  0.04817884, -0.03440627])

In [94]:
np.maximum(x,y)

array([ 0.2973398 ,  2.00236875,  0.10059244,  0.14863274,  0.71001077,
        0.9974245 ,  1.12337863, -0.03440627])

In [95]:
arr = np.random.randn(7)*5

In [96]:
arr

array([-7.70452702, -8.68973357, -1.09328772,  3.5795962 , -5.27374375,
        1.19355415,  3.04127871])

In [97]:
remainder,whole_part  = np.modf(arr)

In [98]:
remainder

array([-0.70452702, -0.68973357, -0.09328772,  0.5795962 , -0.27374375,
        0.19355415,  0.04127871])

In [99]:
whole_part

array([-7., -8., -1.,  3., -5.,  1.,  3.])

In [100]:
# out 인자를 취해 계산 결과를 저장하기
arr

array([-7.70452702, -8.68973357, -1.09328772,  3.5795962 , -5.27374375,
        1.19355415,  3.04127871])

In [101]:
np.sqrt(arr)

C:\Users\user\AppData\Local\Temp/ipykernel_7376/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan,        nan, 1.89198208,        nan,
       1.09249904, 1.74392623])

In [102]:
np.sqrt(arr, arr)

C:\Users\user\AppData\Local\Temp/ipykernel_7376/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan,        nan, 1.89198208,        nan,
       1.09249904, 1.74392623])

In [103]:
arr

array([       nan,        nan,        nan, 1.89198208,        nan,
       1.09249904, 1.74392623])

4.3. 배열을 이용한 배열지향 프로그래밍

In [105]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)

ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [106]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

4.3.1. 배열 연산으로 조건절 표현하기

In [107]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [108]:
result = np.where(cond, xarr, yarr)

In [109]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [110]:
arr = np.random.randn(4, 4)
arr

array([[-1.54727002, -1.19707372, -0.96178138, -0.04221989],
       [ 0.79388082,  0.54976129,  0.54016425,  0.19835172],
       [ 1.02017242,  0.74687717, -1.44672561,  0.19264818],
       [ 0.37725651,  1.58328293, -0.31120092, -0.69161848]])

In [111]:
np.where(arr>0, 1, -1)

array([[-1, -1, -1, -1],
       [ 1,  1,  1,  1],
       [ 1,  1, -1,  1],
       [ 1,  1, -1, -1]])

In [112]:
np.where(arr>0, 2, arr)

array([[-1.54727002, -1.19707372, -0.96178138, -0.04221989],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -1.44672561,  2.        ],
       [ 2.        ,  2.        , -0.31120092, -0.69161848]])

4.3..2. 수학 메서드와 통계 메서드

In [113]:
arr = np.random.randn(5, 4)

arr

array([[ 0.37804981, -0.13834262, -0.55226357,  1.2301077 ],
       [ 0.12955372, -1.28635303, -0.61562632,  0.01421047],
       [-0.18995109, -1.04734945, -1.66389034, -0.61072069],
       [-0.02991587,  2.11594541, -0.48585636, -0.42839694],
       [ 0.15429239,  0.39444104,  0.55705001,  0.83764472]])

In [114]:
arr.mean()

-0.061868551482475075

In [115]:
np.mean(arr)

-0.061868551482475075

In [116]:
arr.sum()

-1.2373710296495015

In [117]:
arr.mean(axis = 1)

array([ 0.22938783, -0.43955379, -0.87797789,  0.29294406,  0.48585704])

In [118]:
arr.sum(axis = 1)

array([ 0.91755132, -1.75821517, -3.51191158,  1.17177624,  1.94342816])

In [119]:
arr.sum(axis=0)

array([ 0.44202896,  0.03834135, -2.76058659,  1.04284525])

In [120]:
arr.sum(0)

array([ 0.44202896,  0.03834135, -2.76058659,  1.04284525])

In [121]:
arr = np.array([0,1,2,3,4,5,6,7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [122]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [123]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

4.3.3. 불리언 배열을 위한 메서드

In [125]:
arr = np.random.randn(100)

In [126]:
(arr>0).sum()

56

In [127]:
bools = np.array([False, False, True, False])

In [129]:
bools.any()

True

In [130]:
bools.all()

False

4.3.4. 정렬

In [135]:
#---- sort 메서드
arr = np.random.randn(6)

In [136]:
arr

array([ 0.50817666, -0.91580025, -0.21333431,  0.34613057,  0.95050369,
       -1.36239809])

In [137]:
arr.sort()

In [138]:
arr

array([-1.36239809, -0.91580025, -0.21333431,  0.34613057,  0.50817666,
        0.95050369])

In [139]:
arr = np.random.randn(5, 3)

In [140]:
arr

array([[ 0.56612504,  0.28595222,  1.32833456],
       [ 1.79599657, -0.42149535,  0.85903776],
       [-1.32582381,  1.43995567, -0.20010634],
       [ 0.51513561,  0.15041467,  1.41800655],
       [ 1.66017954,  1.71558963,  1.13489076]])

In [141]:
arr.sort(1)

In [142]:
arr

array([[ 0.28595222,  0.56612504,  1.32833456],
       [-0.42149535,  0.85903776,  1.79599657],
       [-1.32582381, -0.20010634,  1.43995567],
       [ 0.15041467,  0.51513561,  1.41800655],
       [ 1.13489076,  1.66017954,  1.71558963]])

In [143]:
# sort를 활용하여 배열의 분위수 구하기
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05)*len(large_arr)]

-3.6086865091065206

4.3.5. 집합 관련 함수

In [145]:
names = np.array(['Bob', 'Jason', 'Mini', 'Bob', 'Big', 'Bob'])

In [146]:
np.unique(names)

array(['Big', 'Bob', 'Jason', 'Mini'], dtype='<U5')

In [148]:
ints = np.array([3, 4, 3, 2, 2, 1, 1, 4, 2])

In [149]:
np.unique(ints)

array([1, 2, 3, 4])

In [150]:
sorted(set(names))

['Big', 'Bob', 'Jason', 'Mini']

In [151]:
values =np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

4.4. 배열 데이터의 파일 입출력

In [154]:
arr = np.arange(10)
np.save('some_array', arr)

In [155]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
np.savez('array_archive.npz', a = arr, b = arr)

In [157]:
arch = np.load('array_archive.npz')

In [158]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.savez_compressed('arrays_compressed.npz', a = arr, b = arr)

In [160]:
arch2 = np.load('arrays_compressed.npz')
arch2['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.5. 선형대수

In [162]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8], [10, 11], [9, 12]])

x.dot(y)

array([[ 54,  66],
       [132, 159]])

In [163]:
np.dot(x, y)

array([[ 54,  66],
       [132, 159]])

In [164]:
x@np.ones(3)

array([ 6., 15.])

4.6. 난수 생성

In [166]:
samples = np.random.normal(size=(4, 4))

samples

array([[ 0.33461923,  0.14823424,  0.60882153, -1.8409222 ],
       [ 0.71129252, -1.93417004,  1.11998255,  0.24064017],
       [ 0.06838751,  1.10285211,  0.80284626, -0.34441261],
       [-0.73427745, -0.33112683, -0.89671006,  0.77564755]])

In [171]:
# numpy 난수 생성기 시드값 변경
np.random.seed(1234)

In [173]:
# 격리된 난수 생성기
rng = np.random.RandomState(1234)

rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])