계단 오르내리기 예제
- numpy
1. 계단을 1000번 수행하면서 N차시에 어느 위치에 있는지 알 수 있다.
2. 처음 시작 칸으로부터 최초로 몇 번째에 10칸 이상 떨어지는지 알 수 있다. 
3. 5000회 시뮬레이션을 할 수 있다. 

In [1]:
import numpy as np

In [4]:
nsteps = 1000

draws = np.random.randint(0, 2, size = nsteps)

steps = np.where(draws ==1 , 1, -1)

# 최종 위치
walk = steps.cumsum()

In [5]:
walk.min()

-18

In [6]:
walk.max()

30

In [7]:
(np.abs(walk) >= 10).argmax() # argmax : 가장 큰 값의 인덱스 반환

119

In [8]:
nwalks = 5000

In [9]:
nsteps = 1000

In [10]:
draws = np.random.randint(0, 2, size = (5000, 1000))

In [11]:
steps = np.where(draws == 1, 1, -1)

In [12]:
steps

array([[-1, -1, -1, ..., -1, -1, -1],
       [ 1, -1,  1, ...,  1,  1, -1],
       [-1,  1,  1, ..., -1, -1, -1],
       ...,
       [-1,  1, -1, ..., -1, -1, -1],
       [-1,  1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  1, -1]])

In [15]:
walks = steps.cumsum(axis = 1)

In [16]:
walks

array([[ -1,  -2,  -3, ..., -26, -27, -28],
       [  1,   0,   1, ..., -16, -15, -16],
       [ -1,   0,   1, ...,  74,  73,  72],
       ...,
       [ -1,   0,  -1, ...,   4,   3,   2],
       [ -1,   0,   1, ...,  -4,  -3,  -2],
       [  1,   0,   1, ...,   0,   1,   0]], dtype=int32)

In [17]:
walks.max()

125

In [18]:
walks.min()

-109

In [22]:
hist30 = (np.abs(walks) >= 30).any(axis = 1)

In [23]:
hist30

array([ True,  True,  True, ..., False, False,  True])

In [24]:
hist30.sum()

3351

In [27]:
example = np.array([True, True, False, False, True])

In [28]:
example.sum()

3

In [31]:
crossing_times = np.abs(walks[hist30] >= 30).argmax(1)

In [32]:
crossing_times

array([  0,   0, 423, ..., 573, 889, 557], dtype=int64)

In [33]:
crossing_times.mean()

259.74544911966575